# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-26 09:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20160618_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='cards',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cards.Cards'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comments',
            field=models.TextField(default='', help_text='You can give your thoughts for the card.', verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
